[book]
title        = "Crimpdeq"
description  = "BLE dynamometer designed for finger training"
authors      = ["Sergio Gasquez"]
language     = "en"

[rust]
edition = "2024"

[output.html]
git-repository-url = "https://github.com/crimpdeq/book"
preferred-dark-theme = "ayu"
edit-url-template = "https://github.com/crimpdeq/book/edit/main/{path}"

