[book]
title        = "Crimpdeq"
description  = "Portable digital force sensor designed for climbers, coaches, and therapists to measure and train finger strength, pulling power, and endurance."
authors      = ["Sergio Gasquez"]
language     = "en"

[rust]
edition = "2024"

[output.html]
git-repository-url = "https://github.com/crimpdeq/book"
preferred-dark-theme = "ayu"
edit-url-template = "https://github.com/crimpdeq/book/edit/main/{path}"

